development:
  exhibitor_categories: [Food, Drink, Cookery, Misc]
  exhibitor_ratings:    ["Always welcome", "Well received", "Ok", "Never again"]
  phone_types:          [Mobile, Home, Work, Other]
  results_per_page:     20

test:

production:
